apiVersion: v1
kind: Service
metadata:
  name: lumiere-backend
  namepsace: default
spec:
  type: ClusterIP
  selector:
    app: lumiere-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000