apiVersion: v1
kind: Service
metadata:
  name: lumiere-frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app: lumiere-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30501