apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Chart.Name }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      nodePort: {{ .Values.frontend.service.nodePort }}
